channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - conda=23.3.1
  - pip
  - faiss-gpu
  - faiss-cpu
  - pip:
    - langchain 
    - pypdf2 
    - python-dotenv 
    - streamlit 
    - openai 
    - tiktoken
