name: pdfgpt
channels:
  - javascript
dependencies:
  - python=3.9
  - pip
  - pytorch faiss-gpu
  - pip:
    - langchain 
    - pypdf2 
    - python-dotenv 
    - streamlit 
    - openai 
    - tiktoken
