name: pdfgpt
channels:
  - pytorch
dependencies:
  - python=3.9
  - pip
  - faiss-cpu
  - pip:
    - langchain 
    - pypdf2 
    - python-dotenv 
    - streamlit 
    - openai 
    - tiktoken
